### PR TITLE
Emit error when encountering an unknown preprocessor directive

### LINKED ISSUE #9: Preprocessor ignores unknown directives
Running `sdl-shader-compiler -P` on the source below succeeds with result code 0.
I believe it should fail, or at least warn about an unknown directive.
```c
#unknown directive
```

### PR DESCRIPTION
**Pull request by madebr**
Fixes #9

I also updated the GitHub workflow to make use of [libsdl-org/setup-sdl](https://github.com/libsdl-org/setup-sdl), and run the tests with ctest.

### CODE REVIEW

File: SDL_shader_preprocessor.c [hunk 1]
```diff
@@ -934,6 +935,14 @@ static void handle_pp_error(Context *ctx)
 }
 
 
+static void handle_pp_bad(Context *ctx)
+{
+    IncludeState *state = ctx->include_stack;
+
+    failf(ctx, "unknown directive \"%s\"", state->token);
```
Comment (madebr) [inline SDL_shader_preprocessor.c:942]: This is a lazy to emit the error, and is not a good way to recover from errors.
It's probably better to ignore the rest of the current line.
That way the compiler can emit warnings/errors for more then one issue.

File: SDL_shader_lexer.re [hunk 2]
```diff
@@ -75,8 +75,8 @@ Token preprocessor_lexer(IncludeState *s)
     QUOTE = ["];
 */
 
-    // preprocessor directives are only valid at start of line.
-    if (s->tokenval == ((Token) '\n')) {
+    // preprocessor directives are only valid at start of line, and when not expanding a macro.
+    if (s->tokenval == ((Token) '\n') && !s->expanding_macro) {
```
Comment (madebr) [inline SDL_shader_lexer.re:79]: By re-using `current_define`, there's no need for an extra struct member.
```suggestion
    if (s->tokenval == ((Token) '\n') && s->current_define == NULL) {
```
